- name: install and run nginx
  hosts: web
  become: yes
  tasks: 
  - nmae: insatll nginx pacakage
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx service
    ansible.builtin.service:
      name: nginx
      state: started
