- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNMAE
    prompt: please enter the username
    private: false # use can see what they entering
  - name: PASSWORD
    prompt: please enter the password
    private: true # use can't see what they entering
  tasks:
  - name: print and check the values
    ansible.builtin.debug:
      msg: "username is: {{USERNAME}}, password is: {{PASSWORD}}"