- name: variables from PLAY level
  hosts: localhost
  vars_files:
  - varaibles.yaml
  # vars_prompt:
  # - name: Person
  #   prompt: please enter the Person
  #   private: false # user can see what they entering
  # - name: Wishes
  #   prompt: please enter the Wishes
  #   private: false # user can't see what they entering
  vars: 
    Person: "Siva from PLay"
    Wishes: "Morning from PLAY"
  tasks: 
  - name: check variables
    # vars:
    #   Person: "Siva from task"
    #   Wishes: "Morning from task"
    ansible.builtin.debug:
     msg: "Hello {{Person}}, Good{{Wishes}}"