- name: checking the data types
  hosts: localhost
  vars:
    NAME: Sivakumar
    Skills:
    - Devops
    - AWS
    - Jenkin
    - Docker
    Experience:
      Devops: 6
      Aws: 5
      Java: 8
    Tariner: true
  tasks:
  - name: print key value pair
    ansible.builtin.debug:
      msg: "name: {{NAME}}"

  - name: print list
    ansible.builtin.debug:
      msg: "Skills: {{Skills}}"
  
  - name: print map
    ansible.builtin.debug:
      msg: "Experience: {{Experience}}"

  - name: print boolean
    ansible.builtin.debug:
      msg: "is he Trainer: {{Trainer}}"

  


    


